stages:

- stage: HadolintTests
  jobs:
  - job: AWS
    steps:
    - bash: echo "run AWS tests $(AWS_NAME)" | exit 0
  - job: Azure
    steps:
    - bash: echo "run Azure tests" | exit 1
  - job: GCP
    steps:
    - bash: echo "run GCP tests" | exit 0

- stage: IntegrationTests
  dependsOn: HadolintTests
  condition: succeededOrFailed()
  jobs:
  - job: AWSIT
    condition: in(stageDependencies.HadolintTests.AWS.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')
    steps:
    - bash: echo "This job only runs when AWS Hadolint Test passed"
  - job: AzureIT
    condition: in(stageDependencies.HadolintTests.Azure.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')
    steps:
    - bash: echo "This job only runs when Azure Hadolint Test passed"
  - job: GCPIT
    condition: in(stageDependencies.HadolintTests.GCP.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')
    steps:
    - bash: echo "This job only runs when GCP Hadolint Test passed"