stages:
- stage: Dev
  jobs:
  - job: AA
  - job: BB
    steps:
    - bash: echo "This is Dev"

- stage: HadolintTests
  jobs:
  - job: AWS
    steps:
    - bash: echo "This is bad job" | exit 1
  - job: Azure
    steps:
    - bash: echo "This is good job"

- stage: IntegrationTests
  dependsOn: HadolintTests
  condition: succeededOrFailed()
  jobs:
  - job: AWSIT
    condition: in(stageDependencies.HadolintTests.AWS.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')
    steps:
    - bash: echo "This job only runs when AWS Hadolint Test passed"
  - job: AzureIT
    condition: in(stageDependencies.HadolintTests.Azure.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')
    steps:
    - bash: echo "This job only runs when Azure Hadolint Test passed"