stages:
- stage: Dev
  jobs:
  - job: D1
  - job: D2
    steps:
    - bash: echo "This is Dev"

- stage: Devx
  jobs:
  - job: D3
    steps:
    - bash: echo "This is bad job"
  - job: D4
    steps:
    - bash: echo "This is good job"

- stage: UAT
  dependsOn: Devx
  condition: succeededOrFailed()
  jobs:
  - job: UAT
    steps:
    - bash: echo "This job only runs when Devx fails $stageDependencies.Devx.D3.result"
  - job: UAT2
    steps:
    - bash: echo "This job only runs when Devx fails"
