stages:
- stage: Dev
  jobs:
  - job: AA
  - job: BB
    steps:
    - bash: echo "This is Dev"

- stage: Devx
  jobs:
  - job: DD
    steps:
    - bash: echo "This is bad job"
  - job: EE
    steps:
    - bash: echo "This is good job"

- stage: UAT
  dependsOn: Devx
  condition: succeededOrFailed()
  jobs:
  - job: UAT
    condition: in(stageDependencies.Devx.DD.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')
    steps:
    - bash: echo "This job only runs when Devx fails"
  - job: UAT2
    steps:
    - bash: echo "This job should always run"
